config/routes.rb
CreditDisputeHub::Application.routes.draw do
  resources :disputes
  resources :companies

  resources :sessions
  match "/auth/:provider/callback" => "sessions#create"

end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :user_id, :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider
  attr_accessible :user, :uid, :provider

  def self.find_from_hash(hash)
    find_by_provider_and_uid(hash['provider'], hash['uid'])
  end

  def self.create_from_hash(hash, user = nil)
    user ||= User.create_from_hash!(hash)
    Authorization.create(:user => user, :uid => hash['uid'], :provider => hash['provider'])
  end
end

app/models/company.rb
class Company < ActiveRecord::Base
  validates :name, :presence => true
  has_many :disputes, :dependent => :destroy
  attr_accessible :name, :department, :phone, :fax, :address, :email, :category
end

app/models/dispute.rb
class Dispute < ActiveRecord::Base
  belongs_to :company
  accepts_nested_attributes_for :company
  attr_accessible :title, :company_id, :disputed_amount, :description,
    :private, :company_attributes

  validates :company, :title, :description, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :authorizations
  attr_accessible :name

  def self.create_from_hash!(hash)
    create(:name => hash['info']['name'])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery


protected
  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def signed_in?
    !!current_user
  end

  helper_method :current_user, :signed_in?

  def current_user=(user)
    @current_user = user
    session[:user_id] = user.id
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @companies }
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @company = Company.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/new
  # GET /companies/new.json
  def new
    @company = Company.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(params[:company])

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render json: @company, status: :created, location: @company }
      else
        format.html { render action: "new" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /companies/1
  # PUT /companies/1.json
  def update
    @company = Company.find(params[:id])

    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/disputes_controller.rb
class DisputesController < ApplicationController
  # GET /disputes
  # GET /disputes.json
  def index
    @disputes = Dispute.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @disputes }
    end
  end

  # GET /disputes/1
  # GET /disputes/1.json
  def show
    @dispute = Dispute.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dispute }
    end
  end

  # GET /disputes/new
  # GET /disputes/new.json
  def new
    @dispute = Dispute.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dispute }
    end
  end

  # GET /disputes/1/edit
  def edit
    @dispute = Dispute.find(params[:id])
  end

  # POST /disputes
  # POST /disputes.json
  def create
    @dispute = Dispute.new(params[:dispute])

    respond_to do |format|
      if @dispute.save
        format.html { redirect_to @dispute, notice: 'Dispute was successfully created.' }
        format.json { render json: @dispute, status: :created, location: @dispute }
      else
        format.html { render action: "new" }
        format.json { render json: @dispute.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /disputes/1
  # PUT /disputes/1.json
  def update
    @dispute = Dispute.find(params[:id])

    respond_to do |format|
      if @dispute.update_attributes(params[:dispute])
        format.html { redirect_to @dispute, notice: 'Dispute was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dispute.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /disputes/1
  # DELETE /disputes/1.json
  def destroy
    @dispute = Dispute.find(params[:id])
    @dispute.destroy

    respond_to do |format|
      format.html { redirect_to disputes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    unless @auth = Authorization.find_from_hash(auth_hash)
      # Create a new user or add an auth to existing user, depending on
      # whether there is already a user signed in.
      @auth = Authorization.create_from_hash(auth_hash, current_user)
    end
    # Log the authorizing user in.
    self.current_user = @auth.user

    render :text => "Welcome, #{current_user.name}."
  end

protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/disputes_helper.rb
module DisputesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/companies/_form.html.haml
= f.error_notification
%fieldset
  %legend
    = controller.action_name.capitalize
    Company
  = f.input :name, :label => "Company Name"
  = f.input :department
  = f.input :phone
  = f.input :fax
  = f.input :address, :as => :text
  = f.input :email
  = f.input :category, :hint => "e.g. Auto Loans or Credit Card"

app/views/companies/edit.html.haml
= simple_form_for @company, :html => { :class => "form-horizontal" } do |f|
  = render :partial => "form", :locals => {:f => f}
  .form-actions
    = f.error :base
    = f.button :submit, :class => 'btn-primary'
    = link_to "Cancel", disputes_path, :class => 'btn'

app/views/companies/index.html.haml
%h1 Companies
%table{:class => "table table-striped"}
  %thead
    %tr
      %th ID
      %th
        = t("activerecord.attributes.company.name", :default => t("activerecord.labels.name", :default => "Name"))
      %th Created at
      %th Actions
  %tbody
    - @companies.each do |company|
      %tr
        %td= company.id
        %td= link_to company.name, company_path(company)
        %td= company.created_at
        %td
          = link_to "Show", company_path(company), :class => 'btn btn-mini'
          = link_to "Edit", edit_company_path(company), :class => 'btn btn-mini'
          = link_to "Destroy", company_path(company), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}", :class => 'btn btn-mini btn-danger' 

= link_to "New", new_company_path, :class => 'btn btn-primary'

app/views/companies/new.html.haml
= simple_form_for @company, :html => { :class => 'form-horizontal' } do |f|
  = render :partial => "form", :locals => {:f => f}
  .form-actions
    = f.error :base
    = f.button :submit, :class => 'btn-primary'
    = link_to "Cancel", disputes_path, :class => 'btn'

app/views/companies/show.html.haml
%h1= @company.name

.company-categories
  %span.label= @company.category

%p= @company.department

%p
  %b= t("activerecord.attributes.company.phone", :default => t("activerecord.labels.phone", :default => "Phone")) + ":"
  = @company.phone
%p
  %b= t("activerecord.attributes.company.fax", :default => t("activerecord.labels.fax", :default => "Fax")) + ":"
  = @company.fax
%p
  %b= t("activerecord.attributes.company.address", :default => t("activerecord.labels.address", :default => "Address")) + ":"
  = @company.address
%p
  %b= t("activerecord.attributes.company.email", :default => t("activerecord.labels.email", :default => "Email")) + ":"
  = @company.email

.form-actions
  = link_to "Back", companies_path, :class => 'btn'
  = link_to "Edit", edit_company_path(@company), :class => 'btn'
  = link_to "Delete", company_path(@company), :method => "delete", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}", :class => 'btn'

app/views/disputes/_form.html.haml
= f.error_notification
%fieldset
  %legend
    = controller.action_name.capitalize
    Dispute
  = f.input :title
  = f.association :company, :collection => Company.all.map {|c| [ c.name, c.id ] } + [["Other", '']], :include_blank => false
  #dispute_company_subform.well.hide
    = f.fields_for :company_attributes do |company_fields|
      = render 'companies/form', :f => company_fields
  = f.input :disputed_amount, :wrapper => :prepend do
    %span.add-on $
    = f.input_field :disputed_amount
  = f.input :description, :label => "Describe the problem"
  = f.input :private, :hint => "The dispute will only be visible to you. You will not be able to receive help and advice from other users."
  .form-actions
    = f.error :base
    = f.button :submit, :class => 'btn-primary'
    = link_to "Cancel", disputes_path, :class => 'btn'

app/views/disputes/edit.html.haml
= simple_form_for @dispute, :html => { :class => "edit_dispute form-horizontal" } do |f|
  = render :partial => "form", :locals => {:f => f}

app/views/disputes/index.html.haml
%h1 Disputes
%table{:class => "table table-striped"}
  %thead
    %tr
      %th ID
      %th
        = t("activerecord.attributes.dispute.title", :default => t("activerecord.labels.title", :default => "Title"))
      %th Created at
      %th Actions
  %tbody
    - @disputes.each do |dispute|
      %tr
        %td= dispute.id
        %td= link_to dispute.title, dispute_path(dispute)
        %td= dispute.created_at
        %td
          = link_to "Show", dispute_path(dispute), :class => 'btn btn-mini'
          = link_to "Edit", edit_dispute_path(dispute), :class => 'btn btn-mini'
          = link_to "Destroy", dispute_path(dispute), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}", :class => 'btn btn-mini btn-danger' 

= link_to "New", new_dispute_path, :class => 'btn btn-primary'

app/views/disputes/new.html.haml
= simple_form_for @dispute, :html => { :class => 'form-horizontal' } do |f|
  = render :partial => "form", :locals => {:f => f}

app/views/disputes/show.html.haml
%h1= @dispute.title
%p 
  %b= t("activerecord.attributes.company.name", :default => t("activerecord.labels.company_name", :default => "Company")) + ":"
  = @dispute.company.name
%p 
  %b= t("activerecord.attributes.dispute.disputed_amount", :default => t("activerecord.labels.disputed_amount", :default => "Disputed amount")) + ":"
  = number_to_currency(@dispute.disputed_amount)
%b= t("activerecord.attributes.dispute.description", :default => t("activerecord.labels.description", :default => "Description")) + ":"
%p= @dispute.description

.form-actions
  = link_to "Back", disputes_path, :class => 'btn'
  = link_to "Edit", edit_dispute_path(@dispute), :class => 'btn'
  = link_to "Delete", dispute_path(@dispute), :method => "delete", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}", :class => 'btn'

app/views/layouts/application.html.haml
!!! 5
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %title= content_for?(:title) ? yield(:title) : "CreditDisputeHub"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    / Le styles
    = stylesheet_link_tag "application", :media => "all"
    / Le fav and touch icons
    %link{:href => "images/favicon.ico", :rel => "shortcut icon"}/
    %link{:href => "images/apple-touch-icon.png", :rel => "apple-touch-icon"}/
    %link{:href => "images/apple-touch-icon-72x72.png", :rel => "apple-touch-icon", :sizes => "72x72"}/
    %link{:href => "images/apple-touch-icon-114x114.png", :rel => "apple-touch-icon", :sizes => "114x114"}/


  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand{:href => "#"}CreditDisputeHub
          .container.nav-collapse
            %ul.nav
              %li= link_to "Companies", companies_path
              %li= link_to "Disputes", disputes_path
              %li= link_to "Interactions", "#"

    .container

      .content
        .row
          .span9
            = yield
          .span3
            .well.sidebar-nav
              %h3 Sidebar
              %ul.nav.nav-list
                %li.nav-header Sidebar
                %li= link_to "Link 1", "/path1"
                %li= link_to "Link 2", "/path2"
                %li= link_to "Link 3", "/path3"
    
      %footer
        %p
          &copy; CreditDisputeHub 
          = Date.today.year
    /
      Le javascript
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"